### ISSUE TITLE
aws ha_across_az hard-coded to python 2.6, but currently supported AWS image is 14 (python 2.7)

### ISSUE THREAD

**Issue by landers73** [F5Networks/f5-cloud-libs#10]

**Comment by landers73** [comment]
Apr 11 23:16:56 ugw1g-ltm-003.gapt.to debug aws_advanced_failover[20645]:  command: /opt/aws/awscli-1.10.26/bin/aws ec2 describe-instance-status --instance-id i-017b8430347d8dc66 --output text ended with status 1 had stdout:  and stderr: Traceback (most recent call last):
....
$ source /usr/libexec/aws/common/aws-common-util-prod.sh && source /usr/libexec/aws/common/aws-common.sh && source /usr/libexec/aws/aws-failover-util.sh
$ /opt/aws/awscli-1.10.26/bin/aws ec2 describe-instances
...:
Traceback (most recent call last):
  File "/opt/aws/awscli-1.10.26/bin/aws", line 19, in <module>
    import awscli.clidriver
ImportError: No module named awscli.clidriver

***************************************************************************************************

It will work via the CLI with this, but the scripts use explicit sourcing and inclusion of python 2.6:
----
$ export AWS_HOME=/opt/aws/awscli-1.10.26
$ export PATH=$PATH:$AWS_HOME/bin
$ export PYTHONPATH=$AWS_HOME/lib/python2.7/site-packages:/opt/aws/awscli-1.10.26/lib64/python2.7/site-packages

**Comment by crosbygw** [comment]
Latest release for AWS CFT's has resolved environmental variable problems noted and now support 14.1.

[v4.2.0](https://github.com/F5Networks/f5-aws-cloudformation/tree/v4.2.0)
