### ISSUE TITLE
BIG-IQ revoke doesn't work

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-cloud-libs#22]
With actual version, BIG-IQ revoke doesn't work. The code has changed, since issue https://github.com/F5Networks/f5-cloud-libs/issues/3.
I don't see any revoke action after a scale in is performed. Context: AWS

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with your issue. I've created internal ID ESECLDTPLT-2000 for this bug.

**Comment by amolari** [comment]
sorry to come back with a correction: it works for scale in. I would need some information/pointers on how to call the function. My goal would be to call it when the instances get terminated (deletion of the ASG)

**Comment by ramganesh19** [comment]
same problem is found in Azure autoscale scalein operation that the big-iq license is not revoked.

**Comment by amolari** [comment]
Apparently, this issue has been fixed by ESECLDTPLT-2037, can it be?

**Comment by amolari** [comment]
@ramganesh19 apparently fixed but only in the cloud-libs-aws, apprently. Here the commit link:  https://github.com/F5Networks/f5-cloud-libs-aws/commit/ef88eeb114b996c01ec5daec4f1dc3655abf924d

**Comment by amolari** [comment]
cloud-libs-aws v2.7.0 fixed the issue. Fixed with CFT v5.6.0
