### ISSUE TITLE
BIGIQ licensing, Tenant field to be changed

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-cloud-libs#25]
BIGIQ licensing: the Tenant information doesn't make much sense:
- redundant: we already have the MgmtIP in the field "address"
- not pertinent information with the hostname field (on AWS at least)

In bigIq54LicenseProvider.js, line 182

> tenant: `mgmtAddress=${deviceInfo.managementAddress},hostname=${deviceInfo.hostname}`,

The lack of "real" Tenant information is an issue if we have multiple clusters running (especially in the same VPC => same CIDR): difficult to distinguish which license belongs to which deployment.

I'm asking for the possibility to use a variable value for the tenant field. That variable could then be set in the CFT (AWS) to the customers' wish.

**Comment by andreykashcheev** [comment]
This enhancement is tracked internally using ESECLDTPLT-2062

**Comment by amolari** [comment]
fixed with cloud-libs v4.21.0 (CFT 5.7.0)
