### ISSUE TITLE
Cloud Lib to support revoke license from BIG-IQ

### ISSUE THREAD

**Issue by foobz** [F5Networks/f5-cloud-libs#3]
RFE: Can't find any options to revoke assigned license (return back to pool) from BIG-IQ. Would like to request support of this feature in the cloud library.

**Comment by seattlevine** [comment]
Our autoscale solutions do revoke licenses of BIG-IPs that have been scaled in. Does this fit your use case or do you need to revoke in some other situation?

**Comment by foobz** [comment]
Would you be able to show me where the section for the autoscale revoke licenses?

I am using the cloud-lib to assigned license from BIG-IQ. As part of the orchestration, we are using cloudify and define a flow where during the "uninstall" of the deployment (remove), runs a command to return the licence back to BIG-IQ so that it can reuse. I am using the following command to assign license during the onboarding.

I think it will be great if there are command can be runs (either on BIG-IP or off-box from orchestrator) when destroy the VE, it can runs to return the license back to BIG-IQ

f5-rest-node /config/cloud/f5-cloud-libs/scripts/onboard.js -o /var/log/onboard.log --no-reboot --host localhost --user admin --password ****** --license-pool --big-iq-host 192.168.110.52 --big-iq-user admin --big-iq-password ********* --license-pool-name RegKeyPool

**Comment by seattlevine** [comment]
For our autoscale solutions, autoscale.js runs periodically (about every 2 minutes) on every BIG-IP in the cluster. If it notices that a BIG-IP is in the cluster but not in the autoscale group reported by the cloud provider, it issues a revoke call to BIG-IQ.

The revoke call starts in the cloud specific provider code:
- https://github.com/F5Networks/f5-cloud-libs-aws/blob/master/lib/awsAutoscaleProvider.js#L238
- https://github.com/F5Networks/f5-cloud-libs-azure/blob/master/lib/azureAutoscaleProvider.js#L185

From there it is routed to a specific BIG-IQ version to handle. Look that the bigIq5_*LicenseProvider code
https://github.com/F5Networks/f5-cloud-libs/tree/master/lib

**Comment by garrettdieckmann** [comment]
Looks like seattlevine provided links to the sections of code to answer the question above, and that there haven't been follow-up questions on this item. Closing this issue as resolved.

Thanks!
