### ISSUE TITLE
RFE: Allow assignment of traffic group to self IP address

### ISSUE THREAD

**Issue by edwoodjrjr** [F5Networks/f5-cloud-libs#6]
For Azure failover-api and VNFM use cases, we are going to need to ability to create a floating self IP.  

The ask is to be able to specify a traffic group during self IP creation.

**Comment by edwoodjrjr** [comment]
Forgot to add that since traffic-group-1 will be the only traffic group existing at onboard time, specifying a traffic group should cause that group to be created (with default settings) if not already present.

**Comment by garrettdieckmann** [comment]
This feature was included in version v4.4.0 of f5-cloud-libs. Closing this issue as resolved.

Thanks!
