### ISSUE TITLE
trouble understanding the usage examples

### ISSUE THREAD

**Issue by tthomas0702** [F5Networks/f5-cloud-libs#7]
I am having trouble understanding the usage examples at:
https://github.com/F5Networks/f5-cloud-libs/blob/master/USAGE.md

-- The "License from BIG-IQ" example is:

"admin@(bigip1)(cfg-sync Standalone)(NO LICENSE)(/Common)(tmos)# license path <install_path> password <big_ip_admin_password> big-iq-host <big_iq_ip_address> big-iq-user <big_iq_admin_user> big-iq-password <big_iq_admin_password> license-pool-name <license_pool>"

What is the "license path <install_path>"? 

Are "license path" tmsh keywords?  
I cannot seem to find this while in my tmsh prompt. 

-- In the "Issue revoke request to BIG-IQ" section I have the same confusion as above. 

-- In the "Other licensing options" the shown example, '# license help', gives an error:

Here I am running on a 13.1.0.3 BIG-IP:

root@(skaggs-ltm1)(cfg-sync Standalone)(NO LICENSE)(/Common)(tmos)# license help
Syntax Error: unexpected argument "license"

**Comment by seattlevine** [comment]
The argument to path is the full path to where f5-cloud-libs is installed. For example:
license path /config/cloud/node_modules/@f5devcentral/f5-cloud-libs password...

However, since 'license help' is not working, it looks like the license cli script is not installed. Did you follow the directions here:
https://github.com/F5Networks/f5-cloud-libs/blob/master/USAGE.md#standalone-licensing

**Comment by tthomas0702** [comment]
I installed using the command in the example but from the bash prompt instead of the tmsh prompt like in the example.

Like this:
bash# mkdir -p /config/licensing; cd /config/licensing; npm --loglevel=error install @f5devcentral/f5-cloud-libs

I am able to license a device via BIG-IQ using the onboard.js command running on BIG-IP so it seems to be working. 

In the example, the 'license help' is run from a tmsh prompt. Is it expected that the license cli script can be called from inside tmsh?   

If this is the case perhaps the way I installed caused this to not be available from inside tmsh.

**Comment by seattlevine** [comment]
Yes, it is expected that you run the license script from tmsh. When you ran the install, did you see output like:

> Running on a BIG-IP, installing licensing script.
> Loading license script.
> Creating license alias.

**Comment by tthomas0702** [comment]
I am not sure. I will do a new install, test, and update.

**Comment by tthomas0702** [comment]
It works now that I have run the install from inside tmsh.  Sorry. I did not understand that it was required to run it that way instead of doing an install from the bash prompt. 

It works now. You can close this issue. 
Thanks for the help.
